const cardsData = [
    {
        type: 'cert',
        icon: 'CERT',
        title: 'CJWPT',
        tag: 'Web Pentesting',
        desc: 'Certified Junior Web Penetration Tester — Hack & Fix Academy.',
        img: 'eaf209d6-9494-4ca1-83ec-09ba332df5a5-1.png',
        detailTitle: 'CJWPT',
        detailMeta: 'Hack & Fix Academy — 2026',
        detailDesc: 'Covered OWASP Top 10, manual testing and practical assessment.',
        id: '5',
        pos: 5
    },
    {
        type: 'cert',
        icon: 'CERT',
        title: 'CTDA',
        tag: 'Forensics, Threat Hunting',
        desc: 'Certified Threat Detection Analyst — Hack & Fix Academy.',
        img: 'd8caa1d1-0fb8-4eed-913a-15573c95fadb-1.png',
        detailTitle: 'CTDA',
        detailMeta: 'Hack & Fix Academy — 2026',
        detailDesc: 'Covered ELK Stack and SIEM fundamentals. Hands-on experience with threat detection, log analysis, and incident response.',
        id: '1',
        pos: 1
    },
    {
        type: 'project',
        icon: 'PROJECT',
        title: 'HexGuard',
        tag: 'AI / Security',
        desc: 'A multi-source AI-powered network intrusion detection system (IDS)',
        img: 'screenshot-20260809-152435.png',
        detailTitle: 'HexGuard',
        detailMeta: 'Status: In Progress',
        detailDesc: 'Over the course of my summer internship, I designed and implemented an AI-powered IDS that combines ML-based anomaly detection with rule-based threat hunting. For full documentation : <a href="HexGuard.pdf" download>HexGuard.pdf</a> | <a href="https://github.com/rayen-mansouri/Hexguard.git" target="_blank">GitHub</a>',
        id: '2',
        pos: 2
    },
    {
        type: 'project',
        icon: 'PROJECT',
        title: 'Packet_Analyzer',
        tag: 'Network',
        desc: 'Traffic inspection tool built from the wire up.',
        img: '1776037503717.jpeg',
        detailTitle: 'Packet_Analyzer',
        detailMeta: '',
        detailDesc: 'Parses PCAP files without high‑level libraries. Including graphical interface showcase and reactive attacks flagger. Check it on https://github.com/rayen-mansouri/-Packet_Analyzer',
        id: '6',
        pos: 6
    },
    {
        type: 'project',
        icon: 'PROJECT',
        title: 'Beneath',
        tag: 'Syscall Introspection',
        desc: 'a linux CLI tool for syscalls introspection utility , turning basic "strace" command output into a more comprehensive visualisation.',
        img: 'beneath.jpeg',
        detailTitle: 'Beneath',
        detailMeta: '',
        detailDesc: "Once you run a command through Beneath, you'll get a detailed breakdown including security alerts for privilege escalation, credential access, persistence mechanisms, and network activity, along with a Compare Mode to diff the behavior of two commands side by side and HTML export for reporting. It's especially useful for auditing unknown scripts before running them, solving CTF pwn/binary challenges, and analyzing malware behavior. Learn more and try it here: https://github.com/rayen-mansouri/Beneath",
        id: '4',
        pos: 4
    },
    {
        type: 'cert',
        icon: 'CERT',
        title: 'CLLMSE',
        tag: 'AI Redteaming',
        desc: 'Certified Lead LLM Security Engineer - Red Team Leaders',
        img: 'certified_llm_certificate-1.png',
        detailTitle: 'CLLMSE',
        detailMeta: 'Red Team Leaders — 2026',
        detailDesc: 'Covered LLM security fundamentals, prompt injection, and adversarial attacks. Hands-on experience with LLM security assessment and mitigation strategies.',
        id: '7',
        pos: 7
    },
    {
        type: 'participation',
        icon: 'PARTICIPATION',
        title: '1st place @ CyberSphere Congress 2026',
        tag: 'Team Event',
        desc: 'First place in The CyberSphere Congress 2026 Edition',
        img: '06c83df0-19d9-4f95-ac6a-7436217951bf.jpeg',
        detailTitle: 'CyberSphere Congress 2026',
        detailMeta: '18/04/2026',
        detailDesc: "Our team managed to place first ,even though it was on the beginner's track it gained as an outstading experience and a persisting network",
        id: '3',
        pos: 3
    }
];
